name: Build and Test Workflow

on:
    push:
        branches: []
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Setup Go 
              uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
              with:
                go-version: '1.23'
            - name: Set TCP write buffer settings to the lower minimum of 1 byte
              run: |
                  sysctl net.ipv4.tcp_wmem
                  sudo sysctl -w net.ipv4.tcp_wmem="1 16384 131072"
                  sudo sysctl -p
                  sysctl net.ipv4.tcp_wmem
            - name: Build Go
              run: go build ./...
            - name: Test Go
              run: go test ./...
